In [59]:
import pandas as pd
import numpy as np

# pandas DataFrames

In [3]:
data = pd.read_csv("data.csv")
data.head

<bound method NDFrame.head of    age   first last name
0   32  shivam    sharma
1   24   suman     singh
2   31    shiv     kumar>

In [23]:
data = np.random.randint(2,10,(5,3))

In [24]:
data_dataframe  = pd.DataFrame(data,columns=["col1","col2","col3"])

In [25]:
data_dataframe.head()

   col1  col2  col3
0     6     4     9
1     6     2     8
2     5     2     4
3     3     6     9
4     5     3     8

In [26]:
df = data_dataframe.copy()

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
dtypes: int32(3)
memory usage: 192.0 bytes

In [28]:
df.describe()

           col1     col2      col3
count  5.000000  5.00000  5.000000
mean   5.000000  3.40000  7.600000
std    1.224745  1.67332  2.073644
min    3.000000  2.00000  4.000000
25%    5.000000  2.00000  8.000000
50%    5.000000  3.00000  8.000000
75%    6.000000  4.00000  9.000000
max    6.000000  6.00000  9.000000

In [31]:
data_natest = pd.DataFrame(np.random.randint(2,20,(5,3)),columns=["Col1","Col2","Col3"])
data_natest

   Col1  Col2  Col3
0    10     8    14
1     9     8    19
2    17    17     4
3    19    18    12
4     9     4    12

In [42]:
data_natest.isnull().sum() == 0

Col1    True
Col2    True
Col3    True
dtype: bool

In [48]:
data_natest.iloc[1:2,1:2] = np.nan

In [49]:
data_natest

   Col1  Col2  Col3
0    10   8.0    14
1     9   NaN    19
2    17  17.0     4
3    19  18.0    12
4     9   4.0    12

In [53]:
data_natest.isnull().sum()

Col1    0
Col2    1
Col3    0
dtype: int64

In [54]:
data_natest.value_counts()

Col1  Col2  Col3
9     4.0   12      1
10    8.0   14      1
17    17.0  4       1
19    18.0  12      1
Name: count, dtype: int64

In [57]:
data_natest['Col1'].unique()

array([10,  9, 17, 19], dtype=int32)

In [67]:
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

# Add browser header
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Get webpage content
response = requests.get(url, headers=headers)

html_data = pd.read_html(StringIO(response.text))

In [69]:
html_data[0]

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"

In [70]:
#pickling and Unpickling

import seaborn as sns
df = sns.load_dataset("flights")

In [71]:
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [73]:
df.isnull().sum()

year          0
month         0
passengers    0
dtype: int64

In [74]:
import pickle
filename = "file.pk1"

In [78]:
#pickel and serialize process   
pickle.dump(df,open(filename,'wb'))

In [79]:
#unpickel and unserialize process

pickle.load(open(filename,'rb'))

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]